version: "3"
services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    networks:
      - app

  api:
    build: ./api
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgres://postgres:u!73bG2sanDaL8)d50ax@postgres:5432/development
    depends_on:
      - postgres
    networks:
      - app

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: u!73bG2sanDaL8)d50ax
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app

networks:
  app:
