version = 0.1
[default.deploy.parameters]
stack_name = "caputra-books-api-chi"
resolve_s3 = true
s3_prefix = "caputra-books-api-chi"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
