// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"
	"time"
)

type Booking struct {
	BookingID        int32
	UserID           int32
	CustomerID       int32
	SessionPackageID int32
	SessionDate      time.Time
	Location         sql.NullString
	CreatedAt        sql.NullTime
}

type Customer struct {
	CustomerID   int32
	UserID       int32
	FirstName    string
	LastName     sql.NullString
	EmailAddress string
	MobileNumber sql.NullString
	CreatedAt    sql.NullTime
}

type SessionPackage struct {
	SessionPackageID  int32
	UserID            int32
	Name              string
	SessionTypeID     int32
	DurationInMinutes sql.NullInt32
	Price             int32
	CurrencyCode      sql.NullString
	CreatedAt         sql.NullTime
}

type SessionType struct {
	SessionTypeID int32
	UserID        int32
	Name          string
	Description   sql.NullString
	CreatedAt     sql.NullTime
}

type User struct {
	UserID       int32
	FirstName    string
	LastName     sql.NullString
	EmailAddress string
	MobileNumber sql.NullString
	Password     string
	CreatedAt    sql.NullTime
}
