AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  CapturaGoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/captura-books-api
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          # DATABASE_URL: postgres://captura_books_go:ZpkV4CEVfkMt6ZI@213.188.208.81:5432/captura_books_go?sslmode=disable
          DATABASE_URL: postgresql://joshgermon:jfMlmKA8xB4J@ep-autumn-star-752257-pooler.ap-southeast-1.aws.neon.tech/books
          JWT_SECRET: 47353748675b15f7dc5b65dacd2eaa71355cde8a40b8032e21efc4cd847a82ef

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CapturaGoAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CapturaGoFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt CapturaGoFunction.Arn
  CapturaGoFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt CapturaGoFunctionRole.Arn
